/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ecommerce.kafka.order.avro.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class OrderRequestAvroModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4236820745212545505L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"OrderRequestAvroModel\",\"namespace\":\"com.ecommerce.kafka.order.avro.model\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"sagaId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"inventoryId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"skuId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"warehouseId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"quantity\",\"type\":{\"type\":\"bytes\",\"logicalType\":\"decimal\",\"precision\":10,\"scale\":2}},{\"name\":\"createdAt\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
    MODEL$.addLogicalTypeConversion(new org.apache.avro.Conversions.DecimalConversion());
  }

  private static final BinaryMessageEncoder<OrderRequestAvroModel> ENCODER =
      new BinaryMessageEncoder<OrderRequestAvroModel>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<OrderRequestAvroModel> DECODER =
      new BinaryMessageDecoder<OrderRequestAvroModel>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<OrderRequestAvroModel> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<OrderRequestAvroModel> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<OrderRequestAvroModel> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<OrderRequestAvroModel>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this OrderRequestAvroModel to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a OrderRequestAvroModel from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a OrderRequestAvroModel instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static OrderRequestAvroModel fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String id;
  private java.lang.String sagaId;
  private java.lang.String inventoryId;
  private java.lang.String skuId;
  private java.lang.String warehouseId;
  private java.math.BigDecimal quantity;
  private java.time.Instant createdAt;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public OrderRequestAvroModel() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param sagaId The new value for sagaId
   * @param inventoryId The new value for inventoryId
   * @param skuId The new value for skuId
   * @param warehouseId The new value for warehouseId
   * @param quantity The new value for quantity
   * @param createdAt The new value for createdAt
   */
  public OrderRequestAvroModel(java.lang.String id, java.lang.String sagaId, java.lang.String inventoryId, java.lang.String skuId, java.lang.String warehouseId, java.math.BigDecimal quantity, java.time.Instant createdAt) {
    this.id = id;
    this.sagaId = sagaId;
    this.inventoryId = inventoryId;
    this.skuId = skuId;
    this.warehouseId = warehouseId;
    this.quantity = quantity;
    this.createdAt = createdAt.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return sagaId;
    case 2: return inventoryId;
    case 3: return skuId;
    case 4: return warehouseId;
    case 5: return quantity;
    case 6: return createdAt;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      null,
      null,
      new org.apache.avro.Conversions.DecimalConversion(),
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = value$ != null ? value$.toString() : null; break;
    case 1: sagaId = value$ != null ? value$.toString() : null; break;
    case 2: inventoryId = value$ != null ? value$.toString() : null; break;
    case 3: skuId = value$ != null ? value$.toString() : null; break;
    case 4: warehouseId = value$ != null ? value$.toString() : null; break;
    case 5: quantity = (java.math.BigDecimal)value$; break;
    case 6: createdAt = (java.time.Instant)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.String getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.String value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'sagaId' field.
   * @return The value of the 'sagaId' field.
   */
  public java.lang.String getSagaId() {
    return sagaId;
  }


  /**
   * Sets the value of the 'sagaId' field.
   * @param value the value to set.
   */
  public void setSagaId(java.lang.String value) {
    this.sagaId = value;
  }

  /**
   * Gets the value of the 'inventoryId' field.
   * @return The value of the 'inventoryId' field.
   */
  public java.lang.String getInventoryId() {
    return inventoryId;
  }


  /**
   * Sets the value of the 'inventoryId' field.
   * @param value the value to set.
   */
  public void setInventoryId(java.lang.String value) {
    this.inventoryId = value;
  }

  /**
   * Gets the value of the 'skuId' field.
   * @return The value of the 'skuId' field.
   */
  public java.lang.String getSkuId() {
    return skuId;
  }


  /**
   * Sets the value of the 'skuId' field.
   * @param value the value to set.
   */
  public void setSkuId(java.lang.String value) {
    this.skuId = value;
  }

  /**
   * Gets the value of the 'warehouseId' field.
   * @return The value of the 'warehouseId' field.
   */
  public java.lang.String getWarehouseId() {
    return warehouseId;
  }


  /**
   * Sets the value of the 'warehouseId' field.
   * @param value the value to set.
   */
  public void setWarehouseId(java.lang.String value) {
    this.warehouseId = value;
  }

  /**
   * Gets the value of the 'quantity' field.
   * @return The value of the 'quantity' field.
   */
  public java.math.BigDecimal getQuantity() {
    return quantity;
  }


  /**
   * Sets the value of the 'quantity' field.
   * @param value the value to set.
   */
  public void setQuantity(java.math.BigDecimal value) {
    this.quantity = value;
  }

  /**
   * Gets the value of the 'createdAt' field.
   * @return The value of the 'createdAt' field.
   */
  public java.time.Instant getCreatedAt() {
    return createdAt;
  }


  /**
   * Sets the value of the 'createdAt' field.
   * @param value the value to set.
   */
  public void setCreatedAt(java.time.Instant value) {
    this.createdAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Creates a new OrderRequestAvroModel RecordBuilder.
   * @return A new OrderRequestAvroModel RecordBuilder
   */
  public static com.ecommerce.kafka.order.avro.model.OrderRequestAvroModel.Builder newBuilder() {
    return new com.ecommerce.kafka.order.avro.model.OrderRequestAvroModel.Builder();
  }

  /**
   * Creates a new OrderRequestAvroModel RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new OrderRequestAvroModel RecordBuilder
   */
  public static com.ecommerce.kafka.order.avro.model.OrderRequestAvroModel.Builder newBuilder(com.ecommerce.kafka.order.avro.model.OrderRequestAvroModel.Builder other) {
    if (other == null) {
      return new com.ecommerce.kafka.order.avro.model.OrderRequestAvroModel.Builder();
    } else {
      return new com.ecommerce.kafka.order.avro.model.OrderRequestAvroModel.Builder(other);
    }
  }

  /**
   * Creates a new OrderRequestAvroModel RecordBuilder by copying an existing OrderRequestAvroModel instance.
   * @param other The existing instance to copy.
   * @return A new OrderRequestAvroModel RecordBuilder
   */
  public static com.ecommerce.kafka.order.avro.model.OrderRequestAvroModel.Builder newBuilder(com.ecommerce.kafka.order.avro.model.OrderRequestAvroModel other) {
    if (other == null) {
      return new com.ecommerce.kafka.order.avro.model.OrderRequestAvroModel.Builder();
    } else {
      return new com.ecommerce.kafka.order.avro.model.OrderRequestAvroModel.Builder(other);
    }
  }

  /**
   * RecordBuilder for OrderRequestAvroModel instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<OrderRequestAvroModel>
    implements org.apache.avro.data.RecordBuilder<OrderRequestAvroModel> {

    private java.lang.String id;
    private java.lang.String sagaId;
    private java.lang.String inventoryId;
    private java.lang.String skuId;
    private java.lang.String warehouseId;
    private java.math.BigDecimal quantity;
    private java.time.Instant createdAt;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.ecommerce.kafka.order.avro.model.OrderRequestAvroModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.sagaId)) {
        this.sagaId = data().deepCopy(fields()[1].schema(), other.sagaId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.inventoryId)) {
        this.inventoryId = data().deepCopy(fields()[2].schema(), other.inventoryId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.skuId)) {
        this.skuId = data().deepCopy(fields()[3].schema(), other.skuId);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.warehouseId)) {
        this.warehouseId = data().deepCopy(fields()[4].schema(), other.warehouseId);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.quantity)) {
        this.quantity = data().deepCopy(fields()[5].schema(), other.quantity);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[6].schema(), other.createdAt);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
    }

    /**
     * Creates a Builder by copying an existing OrderRequestAvroModel instance
     * @param other The existing instance to copy.
     */
    private Builder(com.ecommerce.kafka.order.avro.model.OrderRequestAvroModel other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.sagaId)) {
        this.sagaId = data().deepCopy(fields()[1].schema(), other.sagaId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.inventoryId)) {
        this.inventoryId = data().deepCopy(fields()[2].schema(), other.inventoryId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.skuId)) {
        this.skuId = data().deepCopy(fields()[3].schema(), other.skuId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.warehouseId)) {
        this.warehouseId = data().deepCopy(fields()[4].schema(), other.warehouseId);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.quantity)) {
        this.quantity = data().deepCopy(fields()[5].schema(), other.quantity);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[6].schema(), other.createdAt);
        fieldSetFlags()[6] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.String getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.ecommerce.kafka.order.avro.model.OrderRequestAvroModel.Builder setId(java.lang.String value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.ecommerce.kafka.order.avro.model.OrderRequestAvroModel.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'sagaId' field.
      * @return The value.
      */
    public java.lang.String getSagaId() {
      return sagaId;
    }


    /**
      * Sets the value of the 'sagaId' field.
      * @param value The value of 'sagaId'.
      * @return This builder.
      */
    public com.ecommerce.kafka.order.avro.model.OrderRequestAvroModel.Builder setSagaId(java.lang.String value) {
      validate(fields()[1], value);
      this.sagaId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'sagaId' field has been set.
      * @return True if the 'sagaId' field has been set, false otherwise.
      */
    public boolean hasSagaId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'sagaId' field.
      * @return This builder.
      */
    public com.ecommerce.kafka.order.avro.model.OrderRequestAvroModel.Builder clearSagaId() {
      sagaId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'inventoryId' field.
      * @return The value.
      */
    public java.lang.String getInventoryId() {
      return inventoryId;
    }


    /**
      * Sets the value of the 'inventoryId' field.
      * @param value The value of 'inventoryId'.
      * @return This builder.
      */
    public com.ecommerce.kafka.order.avro.model.OrderRequestAvroModel.Builder setInventoryId(java.lang.String value) {
      validate(fields()[2], value);
      this.inventoryId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'inventoryId' field has been set.
      * @return True if the 'inventoryId' field has been set, false otherwise.
      */
    public boolean hasInventoryId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'inventoryId' field.
      * @return This builder.
      */
    public com.ecommerce.kafka.order.avro.model.OrderRequestAvroModel.Builder clearInventoryId() {
      inventoryId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'skuId' field.
      * @return The value.
      */
    public java.lang.String getSkuId() {
      return skuId;
    }


    /**
      * Sets the value of the 'skuId' field.
      * @param value The value of 'skuId'.
      * @return This builder.
      */
    public com.ecommerce.kafka.order.avro.model.OrderRequestAvroModel.Builder setSkuId(java.lang.String value) {
      validate(fields()[3], value);
      this.skuId = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'skuId' field has been set.
      * @return True if the 'skuId' field has been set, false otherwise.
      */
    public boolean hasSkuId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'skuId' field.
      * @return This builder.
      */
    public com.ecommerce.kafka.order.avro.model.OrderRequestAvroModel.Builder clearSkuId() {
      skuId = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'warehouseId' field.
      * @return The value.
      */
    public java.lang.String getWarehouseId() {
      return warehouseId;
    }


    /**
      * Sets the value of the 'warehouseId' field.
      * @param value The value of 'warehouseId'.
      * @return This builder.
      */
    public com.ecommerce.kafka.order.avro.model.OrderRequestAvroModel.Builder setWarehouseId(java.lang.String value) {
      validate(fields()[4], value);
      this.warehouseId = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'warehouseId' field has been set.
      * @return True if the 'warehouseId' field has been set, false otherwise.
      */
    public boolean hasWarehouseId() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'warehouseId' field.
      * @return This builder.
      */
    public com.ecommerce.kafka.order.avro.model.OrderRequestAvroModel.Builder clearWarehouseId() {
      warehouseId = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'quantity' field.
      * @return The value.
      */
    public java.math.BigDecimal getQuantity() {
      return quantity;
    }


    /**
      * Sets the value of the 'quantity' field.
      * @param value The value of 'quantity'.
      * @return This builder.
      */
    public com.ecommerce.kafka.order.avro.model.OrderRequestAvroModel.Builder setQuantity(java.math.BigDecimal value) {
      validate(fields()[5], value);
      this.quantity = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'quantity' field has been set.
      * @return True if the 'quantity' field has been set, false otherwise.
      */
    public boolean hasQuantity() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'quantity' field.
      * @return This builder.
      */
    public com.ecommerce.kafka.order.avro.model.OrderRequestAvroModel.Builder clearQuantity() {
      quantity = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'createdAt' field.
      * @return The value.
      */
    public java.time.Instant getCreatedAt() {
      return createdAt;
    }


    /**
      * Sets the value of the 'createdAt' field.
      * @param value The value of 'createdAt'.
      * @return This builder.
      */
    public com.ecommerce.kafka.order.avro.model.OrderRequestAvroModel.Builder setCreatedAt(java.time.Instant value) {
      validate(fields()[6], value);
      this.createdAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'createdAt' field has been set.
      * @return True if the 'createdAt' field has been set, false otherwise.
      */
    public boolean hasCreatedAt() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'createdAt' field.
      * @return This builder.
      */
    public com.ecommerce.kafka.order.avro.model.OrderRequestAvroModel.Builder clearCreatedAt() {
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public OrderRequestAvroModel build() {
      try {
        OrderRequestAvroModel record = new OrderRequestAvroModel();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.String) defaultValue(fields()[0]);
        record.sagaId = fieldSetFlags()[1] ? this.sagaId : (java.lang.String) defaultValue(fields()[1]);
        record.inventoryId = fieldSetFlags()[2] ? this.inventoryId : (java.lang.String) defaultValue(fields()[2]);
        record.skuId = fieldSetFlags()[3] ? this.skuId : (java.lang.String) defaultValue(fields()[3]);
        record.warehouseId = fieldSetFlags()[4] ? this.warehouseId : (java.lang.String) defaultValue(fields()[4]);
        record.quantity = fieldSetFlags()[5] ? this.quantity : (java.math.BigDecimal) defaultValue(fields()[5]);
        record.createdAt = fieldSetFlags()[6] ? this.createdAt : (java.time.Instant) defaultValue(fields()[6]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<OrderRequestAvroModel>
    WRITER$ = (org.apache.avro.io.DatumWriter<OrderRequestAvroModel>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<OrderRequestAvroModel>
    READER$ = (org.apache.avro.io.DatumReader<OrderRequestAvroModel>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










